# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: formagus tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test library
        uses: borales/actions-yarn@v4
        with:
          cmd: test:ci-coverage
      - name: Install codecov
        run: npx codecov
      - name: Upload coverage to Codecov
        run: codecov --token=:3eda0bdf-2301-4bad-8fcf-0ec45b6e61fa
